/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;

/**
 *
 * @author ASUS
 */
public class framePembelian extends javax.swing.JFrame {

    String id = "";
    java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime());

    /**
     * Creates new form framePembelian
     */
    public framePembelian() {
        initComponents();
    }

    Connection conn;
    PreparedStatement pstmt;
    ResultSet rs;

    public framePembelian(String id) {
        initComponents();
        this.id = id;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldItem = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        radioPayable = new javax.swing.JRadioButton();
        radioCash = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        fieldPay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDetail = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        jLabel3.setText("Nama Penjual");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, -1));

        jLabel5.setText("Item yang dibeli");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 70, -1));
        getContentPane().add(fieldItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, -1));
        getContentPane().add(fieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 70, -1));

        jLabel1.setText("Harga Item / pcs");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 20));

        radioPayable.setText("Account Payable");
        getContentPane().add(radioPayable, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        radioCash.setText("Cash");
        getContentPane().add(radioCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel4.setText("Jumlah Bayar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));
        getContentPane().add(fieldPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 70, -1));

        jLabel6.setText("Keterangan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        fieldDetail.setColumns(20);
        fieldDetail.setRows(5);
        jScrollPane1.setViewportView(fieldDetail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, 60));

        jLabel7.setText("Tambah Pembelian");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jLabel8.setText("Tipe Pembayaran");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 100, -1));

        jLabel2.setText("Banyak Item");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 70, -1));

        jLabel9.setText("Subtotal");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel10.setText("lblSubtotal");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 70, -1));

        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frameTengah ft = new frameTengah(id);
        this.dispose();
        ft.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        validation();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CalcValue();
    }//GEN-LAST:event_jButton3ActionPerformed
    public void CalcValue() {
        Double price = Double.parseDouble(fieldPrice.getText());
        Double qty = Double.parseDouble(jTextField1.getText());
        total = price * qty;
        jLabel10.setText(total.toString());
    }
    Double total = 0d;

    public void validation() {
        boolean con = true;
        if (fieldName.getText().equals("")) {
            con = false;
        }
        if (fieldPay.getText().equals("")) {
            con = false;
        }
        if (fieldItem.getText().equals("")) {
            con = false;
        }
        if (fieldPrice.getText().equals("")) {
            con = false;
        }
        if (fieldDetail.getText().equals("")) {
            con = false;
        }
        if (con) {
            try {
                conn = util.connection.connect();
                if (radioCash.isSelected()) {
                    //nama , item , harga , jumlah , details , date
                    String sql = "Insert into pembelian values(?,?,?,?,?,?)";
                    pstmt = conn.prepareStatement(sql);
                    pstmt.setString(1, fieldName.getText());
                    pstmt.setString(2, fieldItem.getText());
                    pstmt.setString(3, fieldPay.getText());
                    pstmt.setString(4, jTextField1.getText());
                    pstmt.setString(5, fieldPay.getText());
                    pstmt.setString(6, fieldDetail.getText());
                    pstmt.execute();

                    sql = "Insert into jurnal values(?,?,?,?,?,?)";
                    //jurnal ,no akun, debet, kredit, keterangan 
                    pstmt = conn.prepareStatement(sql);
                    pstmt.setDate(1, date);
                    pstmt.setInt(2, 102);
                    pstmt.setString(3, "Persediaan barang");
                    pstmt.setInt(4, Integer.parseInt(fieldPay.getText()));
                    pstmt.setInt(5, 0);
                    pstmt.setString(6, fieldDetail.getText());
                    pstmt.execute();

                    sql = "Insert into jurnal values(?,?,?,?,?,?)";
                    //jurnal ,no akun, debet, kredit, keterangan 
                    pstmt = conn.prepareStatement(sql);
                    pstmt.setDate(1, date);
                    pstmt.setInt(2, 101);
                    pstmt.setString(3, "Kas");
                    pstmt.setInt(5, Integer.parseInt(fieldPay.getText()));
                    pstmt.setInt(4, 0);
                    pstmt.setString(6, fieldDetail.getText());
                    pstmt.execute();

                    Boolean itemExist = checkItemExist();
                    if (itemExist) {
                        try {
                            sql = "update inventory_detail set inventory_detail_total_price = (((inventory_detail_stock*inventory_detail_price)+(?*?))/(inventory_detail_stock+?)),inventory_detail_stock = inventory_detail_stock+? where inventory_id_inventory = ?";
                            pstmt = conn.prepareStatement(sql);
                            pstmt.setInt(1, Integer.parseInt(jTextField1.getText()));
                            pstmt.setInt(2, Integer.parseInt(fieldPrice.getText()));
                            pstmt.setInt(3, Integer.parseInt(jTextField1.getText()));
                            pstmt.setInt(4, Integer.parseInt(jTextField1.getText()));
                            pstmt.setInt(5, checkItemID());
                            System.out.println(pstmt);
                            pstmt.executeUpdate();
                        } catch (SQLException ex) {
                        }
                        if (pstmt.executeUpdate() == 1) {
                            util.Sutil.msg(null, "Updated data");
                        }
                    } else {
                        sql = "insert into inventory name_inventory values (?) ";
                        pstmt = conn.prepareStatement(sql);
                        pstmt.setString(1, fieldItem.getText());
                        pstmt.execute();
                        Integer id = checkItemID();
                        sql = "insert into inventory_detail values ?,?,?,?";
                        //id inventory, stock, price, total price
                        pstmt = conn.prepareStatement(sql);
                        pstmt.setInt(1, id);
                        pstmt.setInt(2, Integer.parseInt(jTextField1.getText()));
                        pstmt.setInt(3, Integer.parseInt(fieldPrice.getText()));
                        pstmt.setInt(4, total.intValue());
                        if (pstmt.execute()) {
                            util.Sutil.msg(null, "created new data");
                        }
                    }

                } else {
                    String sql = "Insert into pembelian values(?,?,?,?,?,?)";
                    pstmt = conn.prepareStatement(sql);
                    pstmt.setString(1, fieldName.getText());
                    pstmt.setString(2, fieldItem.getText());
                    pstmt.setString(3, fieldPay.getText());
                    pstmt.setString(4, jTextField1.getText());
                    pstmt.setString(5, fieldPay.getText());
                    pstmt.setString(6, fieldDetail.getText() + " via credit");
                    pstmt.execute();

                    sql = "Insert into jurnal values(?,?,?,?,?,?)";
                    //jurnal ,no akun, debet, kredit, keterangan 
                    pstmt = conn.prepareStatement(sql);
                    pstmt.setDate(1, date);
                    pstmt.setInt(2, 102);
                    pstmt.setString(3, "Persediaan barang");
                    pstmt.setInt(4, Integer.parseInt(fieldPay.getText()));
                    pstmt.setInt(5, 0);
                    pstmt.setString(6, fieldDetail.getText());
                    pstmt.execute();

                    sql = "Insert into jurnal values(?,?,?,?,?,?)";
                    //jurnal ,no akun, debet, kredit, keterangan 
                    pstmt = conn.prepareStatement(sql);
                    pstmt.setDate(1, date);
                    pstmt.setInt(2, 201);
                    pstmt.setString(3, "Hutang Dagang");
                    pstmt.setInt(5, Integer.parseInt(fieldPay.getText()));
                    pstmt.setInt(4, 0);
                    pstmt.setString(6, fieldDetail.getText());
                    pstmt.execute();

                    Boolean itemExist = checkItemExist();
                    //modify inventory
                    if (itemExist) {
                        try {
                            sql = "update inventory_detail set inventory_detail_total_price = (((inventory_detail_stock*inventory_detail_price)+(?*?))/(inventory_detail_stock+?)),inventory_detail_stock = inventory_detail_stock+? where inventory_id_inventory = ?";
                            pstmt = conn.prepareStatement(sql);
                            pstmt.setInt(1, Integer.parseInt(jTextField1.getText()));
                            pstmt.setInt(2, Integer.parseInt(fieldPrice.getText()));
                            pstmt.setInt(3, Integer.parseInt(jTextField1.getText()));
                            pstmt.setInt(4, Integer.parseInt(jTextField1.getText()));
                            pstmt.setInt(5, checkItemID());
                            System.out.println(pstmt);
                            pstmt.executeUpdate();
                        } catch (SQLException ex) {
                        }
                    } else {
                        sql = "insert into inventory name_inventory values (?) ";
                        pstmt = conn.prepareStatement(sql);
                        pstmt.setString(1, fieldItem.getText());
                        pstmt.execute();
                        Integer id = checkItemID();
                        sql = "insert into inventory_detail values ?,?,?,?";
                        //id inventory, stock, price, total price
                        pstmt = conn.prepareStatement(sql);
                        pstmt.setInt(1, id);
                        pstmt.setInt(2, Integer.parseInt(jTextField1.getText()));
                        pstmt.setInt(3, Integer.parseInt(fieldPrice.getText()));
                        pstmt.setInt(4, total.intValue());
                        if (pstmt.execute()) {
                            util.Sutil.msg(null, "created new data");
                        }
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }

    public int getPriceDatabase() {
        Integer priceDB = 0;
        try {
            String sql = "Select * from inventory_detail where id_inventory = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, dataItem);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                priceDB = rs.getInt("inventory_detail_price");
            }
        } catch (SQLException ex) {

        }
        return priceDB;
    }

    public int getStockDatabase() {
        Integer stockDB = 0;
        try {
            String sql = "Select * from inventory_detail where id_inventory = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, dataItem);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                stockDB = rs.getInt("inventory_detail_stock");
            }
        } catch (SQLException ex) {

        }
        return stockDB;
    }

    public int getAvgPrice() {
        Integer avgPrice = 0;
        try {
            String sql = "Select * from inventory_detail where id_inventory = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, dataItem);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                avgPrice = rs.getInt("inventory_detail_average_price");
            }
        } catch (SQLException ex) {

        }
        return avgPrice;
    }

    public int checkItemID() {
        Integer itemId = 0;
        try {
            String sql = "Select * from inventory where name_inventory = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, fieldItem.getText());
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                itemId = rs.getInt("id_inventory");
            }
        } catch (SQLException ex) {

        }
        return itemId;
    }
    Integer dataItem = 0;

    public boolean checkItemExist() {
        Boolean exists = false;
        try {
            String sql = "Select * from inventory where name_inventory = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, fieldItem.getText());
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                exists = true;
                dataItem = rs.getInt("id_inventory");
            }
        } catch (SQLException ex) {

        }
        return exists;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea fieldDetail;
    private javax.swing.JTextField fieldItem;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPay;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton radioCash;
    private javax.swing.JRadioButton radioPayable;
    // End of variables declaration//GEN-END:variables
}
