package frames;

import dialog.dialogItem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import util.Sutil;

public class frameInventory extends javax.swing.JFrame {

    public frameInventory() {
        initComponents();
    }
    String id;
    Connection conn;
    PreparedStatement pstmt;
    ResultSet rs;

    public frameInventory(String id) {
        setLocationRelativeTo(null);
        initComponents();
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldItem = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel3.setText("Nama Item");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 73, -1));
        getContentPane().add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 70, -1));
        getContentPane().add(fieldItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, -1));
        getContentPane().add(fieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 70, -1));

        jLabel1.setText("Harga Item");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, 20));

        jLabel2.setText("Banyak Item");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setText("Tambah Item Baru");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 80, -1));

        jButton4.setText("Show Item");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frameTengah ft = new frameTengah(id);
        this.dispose();
        ft.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        validation();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        update();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //show dialog for item list
        dialogItem di = new dialogItem(null, false);
        di.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    public void validation() {
        String namaItem = fieldName.getText();
        String banyakItem = fieldItem.getText();
        String hargaItem = fieldPrice.getText();
        try {
            conn = util.connection.connect();
            String sql = "Insert into inventory values(null,?,?,?)";
            pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, namaItem);
            pstmt.setString(2, banyakItem);
            pstmt.setString(3, hargaItem);
            pstmt.executeUpdate();
            
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void update() {
        if (checkItemID() > 0) {
            try {
                String sql = "update inventory_detail set inventory_detail_total_price = (((inventory_detail_stock*inventory_detail_price)+(?*?))/(inventory_detail_stock+?)),inventory_detail_stock = inventory_detail_stock+? where inventory_id_inventory = ?";
                pstmt = conn.prepareStatement(sql);
                pstmt.setInt(4, Integer.parseInt(fieldItem.getText()));
                pstmt.setInt(1, Integer.parseInt(fieldItem.getText()));
                pstmt.setInt(2, Integer.parseInt(fieldPrice.getText()));
                pstmt.setInt(3, Integer.parseInt(fieldItem.getText()));
                pstmt.setInt(5, checkItemID());
                System.out.println(pstmt);
                pstmt.executeUpdate();
                Sutil.msg(this, "Item added");
            } catch (SQLException ex) {

            }
        }
    }

    public int checkItemID() {
        Integer itemId = 0;
        try {
            String sql = "Select * from inventory";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            System.out.println(pstmt);
            while(rs.next()) {
                if (fieldName.getText().equals(rs.getString("name_inventory"))) {
                    itemId = rs.getInt("id_inventory");
                }
            }
        } catch (SQLException ex) {
        }
        return itemId;
    }
    public void loadInventory() {
        
        try {
            String sql = "Select * from inventory";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            System.out.println(pstmt);
            while(rs.next()) {
                
                 DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                Object data[] = {
                        rs.getInt("id_inv"), rs.getString("nama"), rs.getInt("amount"), rs.getDouble("price"),
                }
                tableModel.addRow(data);
            }
        } catch (SQLException ex) {
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldItem;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
